import type { ReactNode } from 'react'
import { AlertCircle, LoaderCircle, SearchX } from 'lucide-react'
import { cn, statusLabel } from '../lib/utils'
import type { Status } from '../lib/types'
export function Panel({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-[18px] border border-[#e0e9f0] bg-white shadow-[0_6px_28px_rgba(15,38,63,.035)]', className)}>{children}</div> }
export function Pill({ status }: { status: Status }) { return <span className={cn('inline-flex gap-1.5 items-center rounded-full px-2.5 py-1 text-[11px] font-bold', { RASCUNHO: 'bg-[#eef2f6] text-[#607488]', PENDENTE: 'bg-[#fff3dc] text-[#956112]', APROVADA: 'bg-[#e1f6ea] text-[#16744b]', REJEITADA: 'bg-[#fae7e9] text-[#a7434e]' }[status])}><span className="size-1.5 rounded-full bg-current"/>{statusLabel[status]}</span> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between mb-7"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#377da9] mb-2">{eyebrow || 'Operação e gestão'}</p><h1 className="text-[27px] sm:text-[31px] font-extrabold tracking-[-.04em] text-[#142b40]">{title}</h1><p className="text-sm text-[#78899a] mt-1">{description}</p></div>{action}</div> }
export function Loading() { return <div className="flex items-center justify-center gap-2 py-16 text-slate-500 text-sm"><LoaderCircle size={18} className="animate-spin"/> Carregando dados...</div> }
export function ErrorBox({ error }: { error: unknown }) { const message = error instanceof Error ? error.message : 'Erro inesperado'; return <div role="alert" className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={18} className="shrink-0"/><div><strong>Não foi possível carregar os dados.</strong><div className="mt-1">{message}</div></div></div> }
export function Empty({ title, description }: { title: string; description: string }) { return <div className="flex flex-col items-center justify-center py-14 px-4 text-center"><div className="size-12 grid place-items-center rounded-2xl bg-[#edf4f9] mb-3 text-[#7392a8]"><SearchX size={23}/></div><h3 className="font-bold text-[#233b50]">{title}</h3><p className="text-sm text-[#8a9aaa] mt-1 max-w-sm">{description}</p></div> }
