import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../lib/api'
import { moeda } from '../lib/utils'
import type { PageProps } from '../App'
import { ErrorBox, Loading, PageHeader, Panel } from '../components/common'
import { Button } from '../components/ui/button'
import { Field, Input, Select, Textarea } from '../components/ui/fields'

type FormItem = { uid:number; descricao:string; quantidade:string; valorUnitario:string }
let nextUid=1
const createItem=():FormItem=>({uid:nextUid++, descricao:'', quantidade:'1',valorUnitario:''})
export default function Solicitar({notify}:PageProps) {
  const navigate=useNavigate()
  const qc=useQueryClient()
  const centros=useQuery({queryKey:['centros'],queryFn:api.centros})
  const fornecedores=useQuery({queryKey:['fornecedores'],queryFn:api.fornecedores})
  const departamentos=useQuery({queryKey:['departamentos'],queryFn:api.departamentos})
  const [centroId,setCentroId]=useState('')
  const [fornecedorId,setFornecedorId]=useState('')
  const [solicitante,setSolicitante]=useState('')
  const [justificativa,setJustificativa]=useState('')
  const [items,setItems]=useState<FormItem[]>(()=>[createItem()])
  const custoAtivos=centros.data?.filter(c=>c.ativo&&departamentos.data?.some(d=>d.id===c.departamentoId&&d.ativo))||[]
  const fornecedoresAtivos=fornecedores.data?.filter(f=>f.ativo)||[]
  const total=useMemo(()=>items.reduce((sum,i)=>sum+(Number(i.quantidade)||0)*(Number(i.valorUnitario)||0),0),[items])
  const save=useMutation({ mutationFn:api.criarSolicitacao, onSuccess:async(s)=>{await qc.invalidateQueries({queryKey:['solicitacoes']});notify(`Solicitação #${s.id} criada com sucesso!`);navigate('/solicitacoes')},onError:e=>notify(e instanceof Error?e.message:'Erro ao criar solicitação','error') })
  const update=(uid:number,key: 'descricao'|'quantidade'|'valorUnitario',value:string)=>setItems(old=>old.map(i=>i.uid===uid?{...i,[key]:value}:i))
  const submit=(e:FormEvent)=>{e.preventDefault();const converted=items.map(i=>({descricao:i.descricao.trim(),quantidade:Number(i.quantidade),valorUnitario:Number(i.valorUnitario)}));if(converted.some(i=>!i.descricao||!Number.isInteger(i.quantidade)||i.quantidade<1||i.quantidade>10000||!Number.isFinite(i.valorUnitario)||i.valorUnitario<=0||Math.abs(Math.round(i.valorUnitario*100)-i.valorUnitario*100)>0.000001)){notify('Confira descrição, quantidade e valores (até 2 casas decimais).','error');return}save.mutate({centroCustoId:Number(centroId),fornecedorId:Number(fornecedorId),solicitante:solicitante.trim(),justificativa:justificativa.trim(),itens:converted})}
  return <><div className="mb-5"><Link to="/solicitacoes" className="inline-flex text-[#5482a3] hover:text-[#126a9b] items-center gap-1.5 text-xs font-bold"><ArrowLeft size={15}/> Voltar para solicitações</Link></div><PageHeader eyebrow="Nova aquisição" title="Criar solicitação" description="Preencha as informações para iniciar o processo de aquisição."/>{centros.isPending||fornecedores.isPending||departamentos.isPending?<Loading/>:centros.isError||fornecedores.isError||departamentos.isError?<ErrorBox error={centros.error||fornecedores.error||departamentos.error}/>:<form onSubmit={submit} className="grid xl:grid-cols-[minmax(0,1fr)_300px] items-start gap-5"><div className="space-y-5"><Panel className="p-6"><div className="border-b pb-4 mb-5 border-[#eaf0f4]"><h2 className="font-extrabold text-[15px]">01 · Informações gerais</h2><p className="text-xs text-[#96a8b6] mt-1">Identificação e justificativa do pedido</p></div><div className="form-grid"><Field label="Nome do solicitante"><Input maxLength={120} required value={solicitante} onChange={e=>setSolicitante(e.target.value)} placeholder="Ex.: Maria Oliveira"/></Field><Field label="Centro de custo"><Select required value={centroId} onChange={e=>setCentroId(e.target.value)}><option value="">Selecione um centro</option>{custoAtivos.map(c=><option key={c.id} value={c.id}>{c.codigo} — {c.nome}</option>)}</Select></Field><Field label="Fornecedor"><Select required value={fornecedorId} onChange={e=>setFornecedorId(e.target.value)}><option value="">Selecione um fornecedor</option>{fornecedoresAtivos.map(f=><option value={f.id} key={f.id}>{f.razaoSocial}</option>)}</Select></Field><div className="sm:col-span-2"><Field label="Justificativa da aquisição"><Textarea maxLength={500} required value={justificativa} onChange={e=>setJustificativa(e.target.value)} placeholder="Descreva a necessidade desta aquisição..."/></Field></div></div>{(custoAtivos.length===0||fornecedoresAtivos.length===0)&&<p role="alert" className="mt-4 text-xs text-[#ac671b] bg-[#fff5e5] border border-[#f3e0bf] rounded-lg px-3 py-2">Cadastre e ative pelo menos um fornecedor e um centro de custo antes de criar a solicitação.</p>}</Panel>
  <Panel className="p-6"><div className="flex items-center justify-between border-b pb-4 mb-5 border-[#eaf0f4]"><div><h2 className="font-extrabold text-[15px]">02 · Itens da solicitação</h2><p className="text-xs text-[#96a8b6] mt-1">Adicione até 30 produtos ou serviços</p></div><Button type="button" variant="outline" size="sm" disabled={items.length>=30} onClick={()=>setItems(old=>[...old,createItem()])}><Plus size={15}/> Adicionar item</Button></div><div className="space-y-3">{items.map((item,index)=><div className="rounded-xl border border-[#e4ebf1] p-4" key={item.uid}><div className="flex justify-between items-center mb-3"><span className="font-bold text-[#33536a] text-xs">Item {index+1}</span><Button type="button" variant="ghost" size="icon" title="Remover item" aria-label="Remover item" disabled={items.length===1} onClick={()=>setItems(old=>old.filter(i=>i.uid!==item.uid))}><Trash2 size={16}/></Button></div><div className="grid sm:grid-cols-[minmax(0,1fr)_110px_145px] gap-3"><Field label="Descrição"><Input required maxLength={200} value={item.descricao} onChange={e=>update(item.uid,'descricao',e.target.value)} placeholder="Ex.: Notebook 16GB"/></Field><Field label="Quantidade"><Input required min={1} max={10000} step="1" type="number" value={item.quantidade} onChange={e=>update(item.uid,'quantidade',e.target.value)}/></Field><Field label="Preço unitário (R$)"><Input required type="number" min="0.01" step="0.01" placeholder="0,00" value={item.valorUnitario} onChange={e=>update(item.uid,'valorUnitario',e.target.value)}/></Field></div><p className="text-xs text-right text-[#728ca0] mt-3">Subtotal: <strong className="text-[#28536c]">{moeda((Number(item.quantidade)||0)*(Number(item.valorUnitario)||0))}</strong></p></div>)}</div></Panel></div>
  <div className="xl:sticky xl:top-5"><Panel className="p-6"><h2 className="font-extrabold text-[16px] text-[#27455d]">Resumo do pedido</h2><div className="mt-6 space-y-4 text-sm"><div className="flex justify-between text-[#8aa0ae]">Itens cadastrados <span className="text-[#254a63] font-bold">{items.length}</span></div><div className="flex justify-between text-[#8aa0ae]">Subtotal <span className="text-[#254a63] font-bold">{moeda(total)}</span></div><div className="h-px bg-[#e5edf3]"/><div className="text-[11px] uppercase font-extrabold tracking-[.12em] text-[#90a4b4]">Total estimado</div><div className="text-[29px] font-['Manrope'] font-extrabold tracking-[-.05em] text-[#1c4f73]">{moeda(total)}</div><p className="text-xs leading-relaxed text-[#98aab8]">A solicitação será criada como rascunho. Depois, envie-a para aprovação.</p><Button className="w-full" type="submit" disabled={save.isPending||!custoAtivos.length||!fornecedoresAtivos.length}><Save size={16}/>{save.isPending?'Salvando...':'Salvar solicitação'}</Button></div></Panel></div></form>}</>
}
